export const ticketPath = 'http://localhost:8686/api/ticket'
export const orderPath = 'http://localhost:8686/api/order'
export const routePath = 'http://localhost:8686/api/route'
export const busPath = 'http://localhost:8686/api/bus'
export const imagePath = 'http://localhost:8686/api/image/'
export const userPath = 'http://localhost:8686/api/user'
export const emailPath = 'http://localhost:8686/api/email'
